# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'Default'
  #vmImage: ubuntu-latest

stages:
- stage: 
  displayName: 'Build my logic App'
 
  jobs:
    - job:
      steps:
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.SourcesDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'

- stage: 
  displayName: 'Deploy to prodution'
  jobs:
    - deployment:
      environment: 'Prod-Logic-Apps'
      strategy: 
       runOnce:
         deploy:
           steps:
            
            - task: DownloadBuildArtifacts@1
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'drop'
                downloadPath: '$(System.ArtifactsDirectory)'

            - task: FuncToolsInstaller@0
              inputs:
                version: 'latest'

            - task: AzureCLI@2
              inputs:
                azureSubscription: 
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  echo deploying the app

                  ls -la

                  cd '$(System.ArtifactsDirectory)/drop'

                  func azure functionapp publish LOGIC-APP-NAME --javascript --nozip --list-ignored-files--list-included-files 
                addSpnToEnvironment: true
                useGlobalConfig: true
